//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentRoomManagement.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RentRoomManagement.Common.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        public static string DevMsg_Bad_Request {
            get {
                return ResourceManager.GetString("DevMsg_Bad_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catched an exception.
        /// </summary>
        public static string DevMsg_Exception {
            get {
                return ResourceManager.GetString("DevMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch thất bại.
        /// </summary>
        public static string DevMsg_Fail_Transaction {
            get {
                return ResourceManager.GetString("DevMsg_Fail_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string DevMsg_Not_Found {
            get {
                return ResourceManager.GetString("DevMsg_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đăng nhập không hợp lệ.
        /// </summary>
        public static string DevMsg_Unauthorized {
            get {
                return ResourceManager.GetString("DevMsg_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu không hợp lệ.
        /// </summary>
        public static string UserMsg_Bad_Request {
            get {
                return ResourceManager.GetString("UserMsg_Bad_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bộ phận sử dụng phải có tiền tố là D, số tăng dần bắt đầu từ 001.
        /// </summary>
        public static string UserMsg_Department_Code {
            get {
                return ResourceManager.GetString("UserMsg_Department_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản đã tồn tại.
        /// </summary>
        public static string UserMsg_Duplicate_Key {
            get {
                return ResourceManager.GetString("UserMsg_Duplicate_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng liên hệ MISA.
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }

        /// <summary>
        /// Thực thi không thành công
        /// </summary>
        public static string UserMsg_Fail_Execution
        {
            get
            {
                return ResourceManager.GetString("UserMsg_Fail_Execution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu thất bại.
        /// </summary>
        public static string UserMsg_Fail {
            get {
                return ResourceManager.GetString("UserMsg_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhiều bản ghi thất bại.
        /// </summary>
        public static string UserMsg_Fail_Delelte_Batch {
            get {
                return ResourceManager.GetString("UserMsg_Fail_Delelte_Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại tài sản phải có tiền tố là AC, số tăng dần bắt đầu từ 001.
        /// </summary>
        public static string UserMsg_Fixed_Asset_Category_Code {
            get {
                return ResourceManager.GetString("UserMsg_Fixed_Asset_Category_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên phải có tiền tố là TS, số tăng dần bắt đầu từ 00001.
        /// </summary>
        public static string UserMsg_Fixed_Asset_Code {
            get {
                return ResourceManager.GetString("UserMsg_Fixed_Asset_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ hao mòn phải bằng 1/Số năm sử dụng.
        /// </summary>
        public static string UserMsg_Life_Time_OR_Depreciation_Rate {
            get {
                return ResourceManager.GetString("UserMsg_Life_Time_OR_Depreciation_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có nhiều attributes được custom cùng kiểu dữ liệu áp dụng vào một property của entity.
        /// </summary>
        public static string UserMsg_Multiple_Attributes_Same_Type {
            get {
                return ResourceManager.GetString("UserMsg_Multiple_Attributes_Same_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu trả về.
        /// </summary>
        public static string UserMsg_Not_Found {
            get {
                return ResourceManager.GetString("UserMsg_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không phù hợp.
        /// </summary>
        public static string UserMsg_Unauthorized {
            get {
                return ResourceManager.GetString("UserMsg_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai kiểu dữ liệu truyền vào.
        /// </summary>
        public static string UserMsg_Wrong_Data_Type {
            get {
                return ResourceManager.GetString("UserMsg_Wrong_Data_Type", resourceCulture);
            }
        }
    }
}
