//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentRoomManagement.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Fields {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fields() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RentRoomManagement.Common.Resources.Fields", typeof(Fields).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên giá.
        /// </summary>
        public static string cost {
            get {
                return ResourceManager.GetString("cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bộ phận sử dụng.
        /// </summary>
        public static string department_code {
            get {
                return ResourceManager.GetString("department_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID bộ phận sử dụng.
        /// </summary>
        public static string department_id {
            get {
                return ResourceManager.GetString("department_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bộ phận sử dụng.
        /// </summary>
        public static string department_name {
            get {
                return ResourceManager.GetString("department_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ hao mòn.
        /// </summary>
        public static string depreciation_rate {
            get {
                return ResourceManager.GetString("depreciation_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại tài sản.
        /// </summary>
        public static string fixed_asset_category_code {
            get {
                return ResourceManager.GetString("fixed_asset_category_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID loại tài sản.
        /// </summary>
        public static string fixed_asset_category_id {
            get {
                return ResourceManager.GetString("fixed_asset_category_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại tài sản.
        /// </summary>
        public static string fixed_asset_category_name {
            get {
                return ResourceManager.GetString("fixed_asset_category_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản.
        /// </summary>
        public static string fixed_asset_code {
            get {
                return ResourceManager.GetString("fixed_asset_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID tài sản.
        /// </summary>
        public static string fixed_asset_id {
            get {
                return ResourceManager.GetString("fixed_asset_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài sản.
        /// </summary>
        public static string fixed_asset_name {
            get {
                return ResourceManager.GetString("fixed_asset_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số năm sử dụng.
        /// </summary>
        public static string life_time {
            get {
                return ResourceManager.GetString("life_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sử dụng.
        /// </summary>
        public static string production_date {
            get {
                return ResourceManager.GetString("production_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua.
        /// </summary>
        public static string purchase_date {
            get {
                return ResourceManager.GetString("purchase_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm theo dõi.
        /// </summary>
        public static string tracked_year {
            get {
                return ResourceManager.GetString("tracked_year", resourceCulture);
            }
        }
    }
}
